-- =====================================================
-- RecallVET Appointments & Encounters
-- CLI-003: Rendez-vous | CLI-004: Consultation médicale
-- =====================================================
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS rv_appointment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  site_id INT DEFAULT NULL,
  animal_id INT NOT NULL,
  party_id INT NOT NULL,
  vet_user_id INT NOT NULL,
  appointment_type ENUM('consultation','vaccination','surgery','follow_up','grooming','other') DEFAULT 'consultation',
  scheduled_date DATE NOT NULL,
  start_time TIME DEFAULT NULL,
  end_time TIME DEFAULT NULL,
  urgency_level ENUM('normal','urgent','emergency') DEFAULT 'normal',
  booking_channel ENUM('phone','whatsapp','walk_in','web','referral') DEFAULT 'walk_in',
  reason TEXT,
  special_instructions TEXT,
  send_reminder TINYINT(1) DEFAULT 0,
  reminder_channel ENUM('sms','whatsapp','email') DEFAULT NULL,
  status ENUM('scheduled','confirmed','checked_in','in_progress','completed','cancelled','no_show') DEFAULT 'scheduled',
  notes TEXT,
  created_by INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES rv_tenant(id) ON DELETE CASCADE,
  FOREIGN KEY (animal_id) REFERENCES rv_animal(id),
  FOREIGN KEY (party_id) REFERENCES rv_party(id),
  INDEX idx_rv_appt_tenant (tenant_id),
  INDEX idx_rv_appt_date (scheduled_date),
  INDEX idx_rv_appt_status (status),
  INDEX idx_rv_appt_vet (vet_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rv_encounter (
  id INT AUTO_INCREMENT PRIMARY KEY,
  tenant_id INT NOT NULL,
  site_id INT DEFAULT NULL,
  appointment_id INT DEFAULT NULL,
  animal_id INT NOT NULL,
  party_id INT NOT NULL,
  vet_user_id INT NOT NULL,
  encounter_date DATETIME NOT NULL,
  encounter_type ENUM('consultation','follow_up','emergency','vaccination','surgery') DEFAULT 'consultation',
  visit_reason TEXT,
  history_presenting_complaint TEXT,
  temperature_c DECIMAL(4,1) DEFAULT NULL,
  heart_rate_bpm INT DEFAULT NULL,
  resp_rate_bpm INT DEFAULT NULL,
  weight_kg DECIMAL(8,2) DEFAULT NULL,
  clinical_findings TEXT,
  diagnostic_hypotheses TEXT,
  primary_diagnosis_code VARCHAR(20) DEFAULT NULL,
  secondary_diagnosis_codes JSON DEFAULT NULL,
  procedures_performed JSON DEFAULT NULL,
  lab_tests_requested JSON DEFAULT NULL,
  prescription_needed TINYINT(1) DEFAULT 0,
  hospitalization_needed TINYINT(1) DEFAULT 0,
  surgery_needed TINYINT(1) DEFAULT 0,
  clinical_plan TEXT,
  follow_up_date DATE DEFAULT NULL,
  owner_instructions TEXT,
  case_status ENUM('open','monitoring','resolved','referred','deceased') DEFAULT 'open',
  status ENUM('draft','in_progress','completed','signed') DEFAULT 'draft',
  signed_at DATETIME DEFAULT NULL,
  signed_by INT DEFAULT NULL,
  created_by INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (tenant_id) REFERENCES rv_tenant(id) ON DELETE CASCADE,
  FOREIGN KEY (appointment_id) REFERENCES rv_appointment(id) ON DELETE SET NULL,
  FOREIGN KEY (animal_id) REFERENCES rv_animal(id),
  FOREIGN KEY (party_id) REFERENCES rv_party(id),
  INDEX idx_rv_enc_tenant (tenant_id),
  INDEX idx_rv_enc_date (encounter_date),
  INDEX idx_rv_enc_animal (animal_id),
  INDEX idx_rv_enc_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
